#! /bin/sh
#AUTOSTART
~/.dotfiles/start.sh &

sxhkd &
picom &
feh --bg-fill ~/.dotfiles/wallpapers/LightTree.png &
$HOME/.config/polybar/launch.sh

laptop=eDP
external_home=HDMI-A-0

if [[ $(xrandr -q | grep "$external_home connected") ]]; then
    echo "Entering multi-screen setup"
    xrandr --output $external_home --primary --mode 1920x1080 --rotate normal --output $laptop --mode 1920x1080 --rotate normal --left-of $external_home
    bspc monitor $external_home -d 1 2 3 4 5 6 7 8 9 10
    bspc monitor $laptop -d w e r t y
else
    echo "Entering single-screen setup"
    xrandr --output $laptop --primary --mode 1920x1080 --rotate normal 
    bspc monitor $laptop -d 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
fi

bspc config border_width         1
bspc config window_gap          7
bsp config presel_feedback_color "#ffffff" 
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner


bspc rule -a Zathura state=tiled
bspc rule -a Todoist desktop='^4' follow=off
bspc rule -a whatsapp-nativefier-d52542 desktop='^1' follow=off
bspc rule -a telegram-desktop='^1' follow=off
bspc rule -a spotify desktop='^2' follow=off

bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config top_padding 1
bspc config bottom_padding 1

border colors 
bspc config focused_border_color "#B48EAD"
bspc config normal_border_color "#454849"
